### ISSUE TITLE
Runtime exception

### ISSUE THREAD

**Issue by barnabynorman** [gmsantos/mongolid-laravel-sample#1]
Hello, I cloned and composer installed and got the following at the end:

`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php71-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php71-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib

                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "5".`

**Comment by gmsantos** [comment]
Looks like is something wrong with your system installation. 

Tested here using Ubuntu 16.04, with default PHP from system (7.0) and installed mongodb driver via pecl.

I dont use Mac here so don't know how to help you further :(
